[workspace]
resolver = "2"
members = ["bindgen", "webview2"]
default-members = ["webview2"]

[workspace.dependencies]
windows-bindgen = { version = "0.100", package = "overrides-windows-bindgen" }
windows-core = "0.100"
windows-registry = "0.100"
webview2 = { path = "webview2", package = "winio-webview2" }
